import type {
  BackgroundColorOption,
  LanguageOption,
  NavLink,
  SizeOption,
  TextSecondaryColorOption,
  TypographyOption,
} from "./types";

export const navLinks: readonly NavLink[] = [
  {
    name: "Προϊόντα",
    en: "Products",
    href: "/products",
    children: [
      { name: "Μπάνιο", href: "/products?category=Μπάνιο" },
      { name: "Κουζίνα", href: "/products?category=Κουζίνα" },
      { name: "Κήπος", href: "/products?category=Κήπος" },
      { name: "Καθαριότητα", href: "/products?category=Καθαριότητα" },
    ],
  },
  {
    name: "Εταιρία",
    en: "About",
    href: "/about",
    children: [
      { name: "Εταιρία", href: "/about" },
      { name: "Βιώσιμη Ανάπτυξη", href: "/sustainability" },
    ],
  },
  { name: "Επικοινωνία", en: "Contact", href: "/contact" },
  { name: "Βιωσιμότητα", en: "Sustainability", href: "#" },
  { name: "Νέα", en: "News", href: "#" },
];

export const languages: readonly LanguageOption[] = [
  { code: "el", label: "Ελληνικά" },
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "de", label: "Deutsch" },
];

export const PALETTE_DEFAULT_VERSION = "chromatic-swatch-2026-05";

export const backgroundColorOptions: readonly BackgroundColorOption[] = [
  {
    code: "sand",
    label: "Sand",
    background: "53 9% 82%",
    card: "53 9% 98%",
    popover: "53 9% 98%",
    muted: "53 9% 82%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 82%",
    sidebarAccent: "53 9% 82%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "mist",
    label: "Mist",
    background: "53 9% 84%",
    card: "53 9% 98%",
    popover: "53 9% 98%",
    muted: "53 9% 84%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 84%",
    sidebarAccent: "53 9% 84%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "ivory",
    label: "Ivory",
    background: "53 9% 86%",
    card: "53 9% 98%",
    popover: "53 9% 98%",
    muted: "53 9% 86%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 86%",
    sidebarAccent: "53 9% 86%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "pearl",
    label: "Pearl",
    background: "53 9% 88%",
    card: "53 9% 98%",
    popover: "53 9% 98%",
    muted: "53 9% 88%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 88%",
    sidebarAccent: "53 9% 88%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "linen",
    label: "Linen",
    background: "53 9% 84%",
    card: "53 9% 98%",
    popover: "53 9% 98%",
    muted: "53 9% 84%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 84%",
    sidebarAccent: "53 9% 84%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "ash",
    label: "Ash",
    background: "53 9% 82%",
    card: "53 9% 96%",
    popover: "53 9% 96%",
    muted: "53 9% 82%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 82%",
    sidebarAccent: "53 9% 82%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "rgb-220-216-207",
    label: "220-216-207",
    background: "53 9% 82%",
    card: "53 9% 96%",
    popover: "53 9% 96%",
    muted: "53 9% 82%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 82%",
    sidebarAccent: "53 9% 82%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "sage-paper",
    label: "Sage Paper",
    background: "53 9% 82%",
    card: "53 9% 96%",
    popover: "53 9% 96%",
    muted: "53 9% 82%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 82%",
    sidebarAccent: "53 9% 82%",
    sidebarBorder: "58 16% 60%",
  },
  {
    code: "custom",
    label: "Custom",
    background: "53 9% 82%",
    card: "53 9% 98%",
    popover: "53 9% 98%",
    muted: "53 9% 82%",
    border: "58 16% 60%",
    input: "58 16% 60%",
    sidebar: "53 9% 82%",
    sidebarAccent: "53 9% 82%",
    sidebarBorder: "58 16% 60%",
  },
];

export const textSecondaryColorOptions: readonly TextSecondaryColorOption[] = [
  {
    code: "viomes-red",
    label: "Viomes Olive",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "forest",
    label: "Forest",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "slate",
    label: "Slate",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "copper",
    label: "Copper",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "teal",
    label: "Teal",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "aubergine",
    label: "Aubergine",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "charcoal",
    label: "Charcoal",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
  {
    code: "custom",
    label: "Custom",
    foreground: "37 25% 13%",
    primary: "46 31% 38%",
    secondary: "63 27% 46%",
    mutedForeground: "37 15% 30%",
    ring: "46 31% 38%",
    sidebarForeground: "37 25% 13%",
  },
];

export const typographyOptions: readonly TypographyOption[] = [
  {
    code: "inter-poppins",
    label: "Inter + Poppins",
    sans: '"Poppins", sans-serif',
    heading: '"Inter", sans-serif',
  },
  {
    code: "manrope-poppins",
    label: "Manrope + Poppins",
    sans: '"Poppins", sans-serif',
    heading: '"Manrope", sans-serif',
  },
  {
    code: "manrope",
    label: "Manrope",
    sans: '"Manrope", sans-serif',
    heading: '"Manrope", sans-serif',
  },
  {
    code: "inter",
    label: "Inter",
    sans: '"Inter", sans-serif',
    heading: '"Inter", sans-serif',
  },
  {
    code: "ibm-plex-sans",
    label: "IBM Plex Sans",
    sans: '"IBM Plex Sans", sans-serif',
    heading: '"IBM Plex Sans", sans-serif',
  },
  {
    code: "source-serif-4",
    label: "Source Serif 4",
    sans: '"Source Serif 4", serif',
    heading: '"Source Serif 4", serif',
  },
  {
    code: "nunito-sans",
    label: "Nunito Sans",
    sans: '"Nunito Sans", sans-serif',
    heading: '"Nunito Sans", sans-serif',
  },
  {
    code: "quicksand",
    label: "Quicksand",
    sans: '"Quicksand", sans-serif',
    heading: '"Quicksand", sans-serif',
  },
  {
    code: "mulish",
    label: "Mulish",
    sans: '"Mulish", sans-serif',
    heading: '"Mulish", sans-serif',
  },
  {
    code: "noto-sans",
    label: "Noto Sans",
    sans: '"Noto Sans", sans-serif',
    heading: '"Noto Sans", sans-serif',
  },
  {
    code: "source-sans-3",
    label: "Source Sans 3",
    sans: '"Source Sans 3", sans-serif',
    heading: '"Source Sans 3", sans-serif',
  },
  {
    code: "rubik",
    label: "Rubik",
    sans: '"Rubik", sans-serif',
    heading: '"Rubik", sans-serif',
  },
  {
    code: "poppins",
    label: "Poppins",
    sans: '"Poppins", sans-serif',
    heading: '"Poppins", sans-serif',
  },
  {
    code: "space-grotesk",
    label: "Space Grotesk",
    sans: '"Space Grotesk", sans-serif',
    heading: '"Space Grotesk", sans-serif',
  },
  {
    code: "lora",
    label: "Lora",
    sans: '"Lora", serif',
    heading: '"Lora", serif',
  },
  {
    code: "merriweather",
    label: "Merriweather",
    sans: '"Merriweather", serif',
    heading: '"Merriweather", serif',
  },
  {
    code: "playfair-display",
    label: "Playfair Display",
    sans: '"Playfair Display", serif',
    heading: '"Playfair Display", serif',
  },
  {
    code: "ibm-plex-serif",
    label: "IBM Plex Serif",
    sans: '"IBM Plex Serif", serif',
    heading: '"IBM Plex Serif", serif',
  },
];

export const sizeOptions: readonly SizeOption[] = [
  { code: "xs", label: "X-Small", scale: 0.8 },
  { code: "sm", label: "Small", scale: 0.9 },
  { code: "md", label: "Medium", scale: 1 },
  { code: "lg", label: "Large", scale: 1.1 },
  { code: "xl", label: "X-Large", scale: 1.2 },
  { code: "xxl", label: "XX-Large", scale: 1.3 },
];

export const baseTextSizes = {
  "--text-xs": "0.75rem",
  "--text-sm": "0.875rem",
  "--text-base": "1rem",
  "--text-lg": "1.125rem",
  "--text-xl": "1.25rem",
  "--text-2xl": "1.5rem",
  "--text-3xl": "1.875rem",
  "--text-4xl": "2.25rem",
  "--text-5xl": "3rem",
  "--text-6xl": "3.75rem",
  "--text-7xl": "4.5rem",
  "--text-8xl": "6rem",
  "--text-9xl": "8rem",
} as const;

export const plainTextSizeKeys = [
  "--text-xs",
  "--text-sm",
  "--text-base",
  "--text-lg",
] as const;

export const titleSizeKeys = [
  "--text-xl",
  "--text-2xl",
  "--text-3xl",
  "--text-4xl",
  "--text-5xl",
  "--text-6xl",
  "--text-7xl",
  "--text-8xl",
  "--text-9xl",
] as const;

const flagEmojiByLanguage: Record<string, string> = {
  el: "🇬🇷",
  en: "🇬🇧",
  fr: "🇫🇷",
  de: "🇩🇪",
};

export const getFlagEmoji = (code: string) =>
  flagEmojiByLanguage[code] ?? flagEmojiByLanguage.en;
