import type {
  BackgroundColorOption,
  LanguageOption,
  NavLink,
  SizeOption,
  TextSecondaryColorOption,
  TypographyOption,
} from "./types";

export const navLinks: readonly NavLink[] = [
  {
    name: "Προϊόντα",
    en: "Products",
    href: "/products",
    children: [
      { name: "Είδη Σπιτιού", href: "/products/eidi-spitioy" },
      { name: "Γλάστρες", href: "/products/glastres" },
      {
        name: "Επαγγελματικός Εξοπλισμός",
        href: "/products/epaggelmatikos-eksoplismos",
      },
    ],
  },
  {
    name: "Η Εταιρεία",
    en: "About",
    href: "/about",
    children: [
      { name: "Η Εταιρεία", href: "/about" },
      { name: "Βιώσιμη Ανάπτυξη", href: "/sustainability" },
    ],
  },
  { name: "Επικοινωνία", en: "Contact", href: "/contact" },
];

export const languages: readonly LanguageOption[] = [
  { code: "el", label: "Ελληνικά" },
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "de", label: "Deutsch" },
];

export const PALETTE_DEFAULT_VERSION = "classic-2026-02";

export const backgroundColorOptions: readonly BackgroundColorOption[] = [
  {
    code: "sand",
    label: "Sand",
    background: "33 17% 90%",
    card: "33 17% 94%",
    popover: "33 17% 94%",
    muted: "33 17% 80%",
    border: "33 17% 74%",
    input: "33 17% 78%",
    sidebar: "33 17% 86%",
    sidebarAccent: "33 17% 80%",
    sidebarBorder: "33 17% 72%",
  },
  {
    code: "mist",
    label: "Mist",
    background: "210 18% 92%",
    card: "210 20% 96%",
    popover: "210 20% 96%",
    muted: "210 15% 84%",
    border: "210 14% 76%",
    input: "210 14% 80%",
    sidebar: "210 15% 88%",
    sidebarAccent: "210 14% 83%",
    sidebarBorder: "210 14% 74%",
  },
  {
    code: "ivory",
    label: "Ivory",
    background: "42 35% 94%",
    card: "42 38% 97%",
    popover: "42 38% 97%",
    muted: "42 22% 86%",
    border: "42 20% 78%",
    input: "42 20% 82%",
    sidebar: "42 26% 90%",
    sidebarAccent: "42 22% 84%",
    sidebarBorder: "42 20% 76%",
  },
  {
    code: "pearl",
    label: "Pearl",
    background: "30 20% 95%",
    card: "30 22% 98%",
    popover: "30 22% 98%",
    muted: "30 14% 88%",
    border: "30 12% 80%",
    input: "30 12% 84%",
    sidebar: "30 16% 91%",
    sidebarAccent: "30 14% 86%",
    sidebarBorder: "30 12% 78%",
  },
  {
    code: "linen",
    label: "Linen",
    background: "18 26% 92%",
    card: "18 30% 96%",
    popover: "18 30% 96%",
    muted: "18 20% 84%",
    border: "18 18% 76%",
    input: "18 18% 80%",
    sidebar: "18 22% 88%",
    sidebarAccent: "18 20% 82%",
    sidebarBorder: "18 18% 74%",
  },
  {
    code: "ash",
    label: "Ash",
    background: "210 8% 90%",
    card: "210 10% 95%",
    popover: "210 10% 95%",
    muted: "210 8% 82%",
    border: "210 8% 74%",
    input: "210 8% 78%",
    sidebar: "210 9% 86%",
    sidebarAccent: "210 8% 80%",
    sidebarBorder: "210 8% 72%",
  },
  {
    code: "rgb-220-216-207",
    label: "220-216-207",
    background: "42 16% 84%",
    card: "42 16% 88%",
    popover: "42 16% 88%",
    muted: "42 12% 76%",
    border: "42 10% 68%",
    input: "42 10% 72%",
    sidebar: "42 13% 80%",
    sidebarAccent: "42 11% 74%",
    sidebarBorder: "42 10% 66%",
  },
  {
    code: "sage-paper",
    label: "Sage Paper",
    background: "118 16% 92%",
    card: "118 18% 96%",
    popover: "118 18% 96%",
    muted: "118 12% 84%",
    border: "118 10% 76%",
    input: "118 10% 80%",
    sidebar: "118 13% 88%",
    sidebarAccent: "118 11% 82%",
    sidebarBorder: "118 10% 74%",
  },
  {
    code: "custom",
    label: "Custom",
    background: "33 17% 90%",
    card: "33 17% 94%",
    popover: "33 17% 94%",
    muted: "33 17% 80%",
    border: "33 17% 74%",
    input: "33 17% 78%",
    sidebar: "33 17% 86%",
    sidebarAccent: "33 17% 80%",
    sidebarBorder: "33 17% 72%",
  },
];

export const textSecondaryColorOptions: readonly TextSecondaryColorOption[] = [
  {
    code: "viomes-red",
    label: "Viomes Red",
    foreground: "2 39% 22%",
    primary: "2 39% 47%",
    secondary: "33 17% 84%",
    mutedForeground: "2 20% 35%",
    ring: "2 39% 47%",
    sidebarForeground: "2 39% 25%",
  },
  {
    code: "forest",
    label: "Forest",
    foreground: "148 34% 19%",
    primary: "148 43% 35%",
    secondary: "148 20% 84%",
    mutedForeground: "148 12% 33%",
    ring: "148 43% 35%",
    sidebarForeground: "148 30% 23%",
  },
  {
    code: "slate",
    label: "Slate",
    foreground: "218 18% 23%",
    primary: "218 28% 40%",
    secondary: "218 18% 85%",
    mutedForeground: "218 12% 38%",
    ring: "218 28% 40%",
    sidebarForeground: "218 16% 28%",
  },
  {
    code: "copper",
    label: "Copper",
    foreground: "19 42% 24%",
    primary: "19 56% 43%",
    secondary: "19 18% 84%",
    mutedForeground: "19 16% 36%",
    ring: "19 56% 43%",
    sidebarForeground: "19 34% 29%",
  },
  {
    code: "teal",
    label: "Teal",
    foreground: "182 54% 20%",
    primary: "182 62% 36%",
    secondary: "182 22% 84%",
    mutedForeground: "182 18% 34%",
    ring: "182 62% 36%",
    sidebarForeground: "182 40% 25%",
  },
  {
    code: "aubergine",
    label: "Aubergine",
    foreground: "318 30% 22%",
    primary: "318 42% 40%",
    secondary: "318 16% 84%",
    mutedForeground: "318 14% 35%",
    ring: "318 42% 40%",
    sidebarForeground: "318 24% 27%",
  },
  {
    code: "charcoal",
    label: "Charcoal",
    foreground: "220 9% 18%",
    primary: "220 12% 34%",
    secondary: "220 10% 82%",
    mutedForeground: "220 8% 33%",
    ring: "220 12% 34%",
    sidebarForeground: "220 8% 24%",
  },
  {
    code: "custom",
    label: "Custom",
    foreground: "2 39% 22%",
    primary: "2 39% 47%",
    secondary: "33 17% 84%",
    mutedForeground: "2 20% 35%",
    ring: "2 39% 47%",
    sidebarForeground: "2 39% 25%",
  },
];

export const typographyOptions: readonly TypographyOption[] = [
  {
    code: "inter-poppins",
    label: "Inter + Poppins",
    sans: '"Poppins", sans-serif',
    heading: '"Inter", sans-serif',
  },
  {
    code: "manrope-poppins",
    label: "Manrope + Poppins",
    sans: '"Poppins", sans-serif',
    heading: '"Manrope", sans-serif',
  },
  {
    code: "manrope",
    label: "Manrope",
    sans: '"Manrope", sans-serif',
    heading: '"Manrope", sans-serif',
  },
  {
    code: "inter",
    label: "Inter",
    sans: '"Inter", sans-serif',
    heading: '"Inter", sans-serif',
  },
  {
    code: "ibm-plex-sans",
    label: "IBM Plex Sans",
    sans: '"IBM Plex Sans", sans-serif',
    heading: '"IBM Plex Sans", sans-serif',
  },
  {
    code: "source-serif-4",
    label: "Source Serif 4",
    sans: '"Source Serif 4", serif',
    heading: '"Source Serif 4", serif',
  },
  {
    code: "nunito-sans",
    label: "Nunito Sans",
    sans: '"Nunito Sans", sans-serif',
    heading: '"Nunito Sans", sans-serif',
  },
  {
    code: "quicksand",
    label: "Quicksand",
    sans: '"Quicksand", sans-serif',
    heading: '"Quicksand", sans-serif',
  },
  {
    code: "mulish",
    label: "Mulish",
    sans: '"Mulish", sans-serif',
    heading: '"Mulish", sans-serif',
  },
  {
    code: "noto-sans",
    label: "Noto Sans",
    sans: '"Noto Sans", sans-serif',
    heading: '"Noto Sans", sans-serif',
  },
  {
    code: "source-sans-3",
    label: "Source Sans 3",
    sans: '"Source Sans 3", sans-serif',
    heading: '"Source Sans 3", sans-serif',
  },
  {
    code: "rubik",
    label: "Rubik",
    sans: '"Rubik", sans-serif',
    heading: '"Rubik", sans-serif',
  },
  {
    code: "poppins",
    label: "Poppins",
    sans: '"Poppins", sans-serif',
    heading: '"Poppins", sans-serif',
  },
  {
    code: "space-grotesk",
    label: "Space Grotesk",
    sans: '"Space Grotesk", sans-serif',
    heading: '"Space Grotesk", sans-serif',
  },
  {
    code: "lora",
    label: "Lora",
    sans: '"Lora", serif',
    heading: '"Lora", serif',
  },
  {
    code: "merriweather",
    label: "Merriweather",
    sans: '"Merriweather", serif',
    heading: '"Merriweather", serif',
  },
  {
    code: "playfair-display",
    label: "Playfair Display",
    sans: '"Playfair Display", serif',
    heading: '"Playfair Display", serif',
  },
  {
    code: "ibm-plex-serif",
    label: "IBM Plex Serif",
    sans: '"IBM Plex Serif", serif',
    heading: '"IBM Plex Serif", serif',
  },
];

export const sizeOptions: readonly SizeOption[] = [
  { code: "xs", label: "X-Small", scale: 0.8 },
  { code: "sm", label: "Small", scale: 0.9 },
  { code: "md", label: "Medium", scale: 1 },
  { code: "lg", label: "Large", scale: 1.1 },
  { code: "xl", label: "X-Large", scale: 1.2 },
  { code: "xxl", label: "XX-Large", scale: 1.3 },
];

export const baseTextSizes = {
  "--text-xs": "0.75rem",
  "--text-sm": "0.875rem",
  "--text-base": "1rem",
  "--text-lg": "1.125rem",
  "--text-xl": "1.25rem",
  "--text-2xl": "1.5rem",
  "--text-3xl": "1.875rem",
  "--text-4xl": "2.25rem",
  "--text-5xl": "3rem",
  "--text-6xl": "3.75rem",
  "--text-7xl": "4.5rem",
  "--text-8xl": "6rem",
  "--text-9xl": "8rem",
} as const;

export const plainTextSizeKeys = [
  "--text-xs",
  "--text-sm",
  "--text-base",
  "--text-lg",
] as const;

export const titleSizeKeys = [
  "--text-xl",
  "--text-2xl",
  "--text-3xl",
  "--text-4xl",
  "--text-5xl",
  "--text-6xl",
  "--text-7xl",
  "--text-8xl",
  "--text-9xl",
] as const;

const flagEmojiByLanguage: Record<string, string> = {
  el: "🇬🇷",
  en: "🇬🇧",
  fr: "🇫🇷",
  de: "🇩🇪",
};

export const getFlagEmoji = (code: string) =>
  flagEmojiByLanguage[code] ?? flagEmojiByLanguage.en;
